apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - dss
  containers:
    - name: curl-container
      image: "curlimages/curl:8.5.0"
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Sleeping indefinitely..."
          sleep infinity