apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  restartPolicy: Never
  volumes:
    - name: home-volume
      persistentVolumeClaim:
        claimName: dsmillerrunfol-rwm
  containers:
    - name: curl-container
      image: "curlimages/curl:8.5.0"
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
      volumeMounts:
        - name: home-volume
          mountPath: /kube/home/
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Sleeping indefinitely..."
          sleep infinity