apiVersion: v1
kind: Pod
metadata:
  name: filestore
spec:
  restartPolicy: Always
  securityContext:
    runAsUser: 71032
    runAsGroup: 9915
  volumes:
    - name: geograd
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd
  containers:
    - name: conda-container
      image: "nvidia/samples:vectoradd-cuda11.2.1"
      volumeMounts:
        - name: geograd
          mountPath: /sciclone/geograd/
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Disk space usage for /kube/home volume:"
          df -h /kube/home
          echo "Sleeping indefinitely..."
          sleep infinity
