apiVersion: v1
kind: Pod
metadata:
  name: conda
spec:
  restartPolicy: OnFailure
  securityContext:
    runAsUser: 71032
    runAsGroup: 9915
  volumes:
    - name: geograd
      nfs:
        server: 128.239.59.144
        path: /sciclone/geograd
  containers:
    - name: conda-container
      image: "condaforge/mambaforge"
      resources:
        requests:
          memory: "8Gi"
          cpu: "2"
      volumeMounts:
        - name: geograd
          mountPath: /sciclone/geograd/
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Sleeping indefinitely..."
          sleep infinity
