apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-base
spec:
  restartPolicy: Never
  volumes:
    - name: home-volume
      persistentVolumeClaim:
        claimName: dsmillerrunfol-rwm
  containers:
    - name: ubuntu-container
      image: "ubuntu:latest"
      resources:
        requests:
          memory: "8Gi"
          cpu: "2"
      volumeMounts:
        - name: home-volume
          mountPath: /kube/home/
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Sleeping indefinitely..."
          sleep infinity