apiVersion: v1
kind: Pod
metadata:
  name: osrm-ex
spec:
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - dss
  volumes:
    - name: home-volume
      persistentVolumeClaim:
        claimName: dsmillerrunfol-rwm
  containers:
    - name: conda-container
      image: "condaforge/mambaforge"
      resources:
        requests:
          memory: "8Gi"
          cpu: "2"
      volumeMounts:
        - name: home-volume
          mountPath: /kube/home/
      command: ["/bin/sh", "-c"]
      args:
        - |
          ENV_PATH="/kube/home/.envs/osrm"
          conda activate $ENV_PATH
          python /kube/home/git/kubeApps/openrouteservice/example.py