apiVersion: v1
kind: Pod
metadata:
  name: osm-preprocessing
spec:
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - dss
  volumes:
    - name: osm-data-volume
      persistentVolumeClaim:
        claimName: dsmillerrunfol-rwm
  containers:
    - name: osmr-preprocessing
      image: ghcr.io/project-osrm/osrm-backend:latest
      resources:
        requests:
          memory: "8Gi"
          cpu: "2"
      volumeMounts:
        - name: osm-data-volume
          mountPath: "/data/"
          subPath: git/kubeApps/openrouteservice/data
      command: ["/bin/sh", "-c"]
      args:
        - |
          ENV_PATH="/kube/home/.envs/osrm"
          source activate $ENV_PATH
          ls /data/
          sleep 999999999999;