apiVersion: v1
kind: Service
metadata:
  name: osrm
  labels:
    app: osrm
spec:
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32513
    name: http
  selector:
    app: osrm
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm
  labels:
    app: osrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osrm
  template:
    metadata:
      labels:
        app: osrm
    spec:
      containers:
      - name: osrm
        image: ghcr.io/project-osrm/osrm-backend:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "12Gi"
            cpu: "1"
          limits:
            memory: "12Gi"
            cpu: "1"
        command: ["/bin/sh", "-c"]
        args: ["osrm-routed --algorithm mld /data/nepal-latest.osm.pbf"]
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: osm-data-volume
          readOnly:  true
          mountPath: "/data/"
          subPath: git/kubeApps/openrouteservice/data
      volumes:
      - name: osm-data-volume
        persistentVolumeClaim:
          claimName: dsmillerrunfol-rwm