apiVersion: v1
kind: Pod
metadata:
  name: rmq-generator
spec:
  restartPolicy: Never
  volumes:
    - name: kubehome
      persistentVolumeClaim:
        claimName: dsmillerrunfol-rwm
  containers:
    - name: producer
      image: "condaforge/mambaforge"
      resources:
        requests:
          memory: "8Gi"
          cpu: "2"
      env:
        - name: RABBITMQ_SERVICE
          value: "rabbitmq"  # Replace with your RabbitMQ service name
        - name: RABBITMQ_PORT
          value: "5672"      # Replace with your RabbitMQ port
      volumeMounts:
        - name: kubehome
          mountPath: /kube/home  
      command: ["/bin/bash", "-c"]
      args:
        - |
          cd /kube/home/git/kubeApps/RabbitMQ/
          git pull
          source activate /kube/home/.envs/rabbitmq
          python queueGenerator.py