apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
spec:
  containers:
    - name: rabbitmq
      image: rabbitmq:3
      ports:
        - containerPort: 5672
          name: amqp
      volumeMounts:
        - name: rabbitmq-storage
          mountPath: /var/lib/rabbitmq  # The path where RabbitMQ stores data
          subPath: databases/rabbitmq/example # The path on the persistent volume to map it to
  volumes:
    - name: rabbitmq-storage
      persistentVolumeClaim:
        claimName: dsmillerrunfol-rwm