apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-worker
spec:
  volumes:
    - name: kubehome
      persistentVolumeClaim:
        claimName: dsmillerrunfol-rwm
  containers:
    - name: producer
      image: your-producer-image
      env:
        - name: RABBITMQ_SERVICE
          value: "rabbitmq"  # Replace with your RabbitMQ service name
        - name: RABBITMQ_PORT
          value: "5672"      # Replace with your RabbitMQ port
      volumeMounts:
        - name: kubehome
          mountPath: /kube/home  
      command: ["/bin/sh", "-c"]
      args:
        - |
          cd /kube/home/git/kubeApps/RabbitMQ/
          python worker.py