apiVersion: v1
kind: Pod
metadata:
  name: rmq-worker
spec:
  volumes:
    - name: kubehome
      persistentVolumeClaim:
        claimName: dsmillerrunfol-rwm
  containers:
    - name: producer
      image: "condaforge/mambaforge"
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      resources:
        requests:
          memory: "8Gi"
          cpu: "1"
      env:
        - name: RABBITMQ_SERVICE
          value: "rabbitmq"  # Replace with your RabbitMQ service name
        - name: RABBITMQ_PORT
          value: "5672"      # Replace with your RabbitMQ port
      volumeMounts:
        - name: kubehome
          mountPath: /kube/home  
      command: ["/bin/bash", "-c"]
      args:
        - |
          cd /kube/home/git/kubeApps/RabbitMQ/
          echo "Activating."
          source activate /kube/home/.envs/rabbitmq
          echo "Activated, running python process."
          python worker.py