apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-queue
  template:
    metadata:
      labels:
        app: postgres-queue
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret  # Name of your secret
                  key: database          # Key for the database name in your secret
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret  # Name of your secret
                  key: username          # Key for the username in your secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret  # Name of your secret
                  key: password          # Key for the password in your secret
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: databases/postgres/queue
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: dsmillerrunfol-rwm
