apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-queue
  template:
    metadata:
      labels:
        app: postgres-queue
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: dsmillerrunfol-rwm
            readOnly: false
