apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-queue
  template:
    metadata:
      labels:
        app: postgres-queue
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:latest
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: databases/postgres/queue
          resources:
            requests:
              cpu: "8"
              memory: "16Gi"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: dsmillerrunfol-rwm
